Repository SI705-SI63-Tayta/TP_Arqui_Web, pull requests merged in 2024-08, with the labels that each got.

#1 raiz y entities
  .gitignore
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/pe/edu/upc/taytagrupo5/TaytaGrupo5Application.java
  src/main/java/pe/edu/upc/taytagrupo5/entities/User.java
  src/main/resources/application.properties
  src/test/java/pe/edu/upc/taytagrupo5/TaytaGrupo5ApplicationTests.java
Labels: enhancement

#2 repositories y dtos añadidos
  src/main/java/pe/edu/upc/taytagrupo5/dtos/UserDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/repositories/IUserRepository.java
Labels: enhancement

#3 controllers
  src/main/java/pe/edu/upc/taytagrupo5/controllers/UserController.java
Labels: enhancement

#4 serviceinterface
  src/main/java/pe/edu/upc/taytagrupo5/serviceinterfaces/IUserService.java
Labels: enhancement

#5 implements
  src/main/java/pe/edu/upc/taytagrupo5/serviceimplements/UserServiceImplement.java
Labels: enhancement

#6 Appointment ent,repo,dto,serv,control
  src/main/java/pe/edu/upc/taytagrupo5/controllers/AppointmentController.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/AppointmentDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/entities/Appointment.java
  src/main/java/pe/edu/upc/taytagrupo5/repositories/IAppointmentRepository.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceimplements/AppointmentServiceImplement.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceinterfaces/IAppointmentService.java
Labels: enhancement

#7 recetas, entities, repository, services, controllers
  src/main/java/pe/edu/upc/taytagrupo5/controllers/RecipesController.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/RecipesDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/entities/Recipes.java
  src/main/java/pe/edu/upc/taytagrupo5/repositories/IRecipesRepository.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceimplements/RecipesServiceImplement.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceinterfaces/IRecipesService.java
Labels: enhancement

#8 entities repositories services dtos Review
  src/main/java/pe/edu/upc/taytagrupo5/controllers/ReviewController.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/ReviewDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/entities/Review.java
  src/main/java/pe/edu/upc/taytagrupo5/repositories/IReviewRepository.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceimplements/ReviewServiceImplement.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceinterfaces/IReviewService.java
  src/main/resources/application.properties
Labels: enhancement

#9 app prop modified
  src/main/resources/application.properties
Labels: bug

#10 crud user
  src/main/java/pe/edu/upc/taytagrupo5/controllers/UserController.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/UserDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceimplements/UserServiceImplement.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceinterfaces/IUserService.java
Labels: enhancement

#11 rol ent,dto,control,repo,serv
  src/main/java/pe/edu/upc/taytagrupo5/controllers/RolController.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/QuantityUserPerRolDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/RolDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/entities/Medical_record.java
  src/main/java/pe/edu/upc/taytagrupo5/entities/Rol.java
  src/main/java/pe/edu/upc/taytagrupo5/repositories/IRolRepository.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceimplements/RolServiceImplement.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceinterfaces/IRolServices.java
Labels: enhancement

#12 relation rol-user
  src/main/java/pe/edu/upc/taytagrupo5/controllers/RolController.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/QuantityUserPerRolDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/RolDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/UserDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/entities/Medical_record.java
  src/main/java/pe/edu/upc/taytagrupo5/entities/Rol.java
  src/main/java/pe/edu/upc/taytagrupo5/entities/User.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceimplements/RolServiceImplement.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceinterfaces/IRolServices.java
Labels: bug, enhancement
