Repository SI705-SI63-Tayta/TP_Arqui_Web, pull requests merged in 2024-09, with the labels that each got.

#13 quantityUserPerRol added and bug rel user-rol
  src/main/java/pe/edu/upc/taytagrupo5/controllers/RolController.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/AppointmentDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/RolDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/UserDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/entities/Rol.java
  src/main/java/pe/edu/upc/taytagrupo5/repositories/IRolRepository.java
Labels: bug, enhancement

#15 Rama de antonio
  src/main/java/pe/edu/upc/taytagrupo5/serviceinterfaces/INotificationsService.java
Labels: enhancement

#16 repositorio e implemnts
  src/main/java/pe/edu/upc/taytagrupo5/repositories/INotificationsRepository.java
  src/main/java/pe/edu/upc/taytagrupo5/repositories/IRolRepository.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceimplements/NotificationsServiceImplements.java
Labels: enhancement

#17 dto y controller
  src/main/java/pe/edu/upc/taytagrupo5/controllers/NotificationController.java
  src/main/java/pe/edu/upc/taytagrupo5/controllers/RolController.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/AppointmentDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/NotificationsDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/RolDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/UserDTO.java
Labels: enhancement

#18 Medical Record entitis, dto, repository, services
  src/main/java/pe/edu/upc/taytagrupo5/controllers/MedicalRecordController.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/MedicalRecordDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/RecipesDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/entities/MedicalRecord.java
  src/main/java/pe/edu/upc/taytagrupo5/entities/Recipes.java
  src/main/java/pe/edu/upc/taytagrupo5/repositories/IMedicalRecordRepository.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceimplements/MedicalRecordServiceImplement.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceinterfaces/IMedicalRecordService.java
Labels: enhancement

#19 bugs fixed relation user-rol
  src/main/java/pe/edu/upc/taytagrupo5/controllers/NotificationController.java
  src/main/java/pe/edu/upc/taytagrupo5/controllers/RecipeController.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/NotificationDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/RecipeDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/entities/Notification.java
  src/main/java/pe/edu/upc/taytagrupo5/entities/Recipe.java
  src/main/java/pe/edu/upc/taytagrupo5/entities/Rol.java
  src/main/java/pe/edu/upc/taytagrupo5/repositories/INotificationRepository.java
  src/main/java/pe/edu/upc/taytagrupo5/repositories/IRecipeRepository.java
  src/main/java/pe/edu/upc/taytagrupo5/repositories/IRecipesRepository.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceimplements/NotificationServiceImplements.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceimplements/NotificationsServiceImplements.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceimplements/RecipeServiceImplement.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceimplements/RecipesServiceImplement.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceinterfaces/INotificationService.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceinterfaces/INotificationsService.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceinterfaces/IRecipeService.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceinterfaces/IRecipesService.java
Labels: bug

#20 Rama de alberto
  src/main/java/pe/edu/upc/taytagrupo5/controllers/ClinicalHistoryDetailController.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/ClinicalHistoryDetailDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/QuantityUserPerRolDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/entities/ClinicalHistoryDetail.java
  src/main/java/pe/edu/upc/taytagrupo5/repositories/IClinicalHistoryDetailRepository.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceimplements/ClinicalHistoryDetailServiceImplement.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceinterfaces/IClinicalHistoryDetailService.java
Labels: enhancement

#21 relation MedicalRecord and ClinicalHistoryDetail
  src/main/java/pe/edu/upc/taytagrupo5/dtos/ClinicalHistoryDetailDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/entities/ClinicalHistoryDetail.java
Labels: bug, enhancement

#22 añadiendo entidad actividades diarias
  src/main/java/pe/edu/upc/taytagrupo5/entities/DailyActivities.java
Labels: enhancement

#23 añadiendo tabla actividades diarias por completo
  src/main/java/pe/edu/upc/taytagrupo5/controllers/DailyActivitiesController.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/DailyActivitiesDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/entities/DailyActivities.java
  src/main/java/pe/edu/upc/taytagrupo5/repositories/IDailyActivitiesRepository.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceimplements/DailyActivitiesServiceImplement.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceinterfaces/IDailyActivitiesService.java
Labels: enhancement

#24 relations review-user and user-appointment
  src/main/java/pe/edu/upc/taytagrupo5/dtos/AppointmentDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/ReviewDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/entities/Appointment.java
  src/main/java/pe/edu/upc/taytagrupo5/entities/Recipe.java
  src/main/java/pe/edu/upc/taytagrupo5/entities/Review.java
Labels: enhancement

#25 fixed dailyActivities
  src/main/java/pe/edu/upc/taytagrupo5/controllers/DailyActivitiesController.java
  src/main/java/pe/edu/upc/taytagrupo5/entities/DailyActivities.java
Labels: bug

#28 queries added and sec removed
  src/main/java/pe/edu/upc/taytagrupo5/controllers/AppointmentController.java
  src/main/java/pe/edu/upc/taytagrupo5/controllers/RecipeController.java
  src/main/java/pe/edu/upc/taytagrupo5/controllers/ReviewController.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/CantidadModalidadCitaDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/CantidadRecetasFinalizadasClienteDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/Top5PersonalDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/repositories/IAppointmentRepository.java
  src/main/java/pe/edu/upc/taytagrupo5/repositories/IMedicalRecordRepository.java
  src/main/java/pe/edu/upc/taytagrupo5/repositories/IRecipeRepository.java
  src/main/java/pe/edu/upc/taytagrupo5/repositories/IReviewRepository.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceimplements/AppointmentServiceImplement.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceimplements/RecipeServiceImplement.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceimplements/ReviewServiceImplement.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceinterfaces/IAppointmentService.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceinterfaces/IRecipeService.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceinterfaces/IReviewService.java
Labels: enhancement

#29 queries quantityuserrol,some bugs
  src/main/java/pe/edu/upc/taytagrupo5/controllers/RolController.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/RecipeDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/UserDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/entities/Recipe.java
  src/main/java/pe/edu/upc/taytagrupo5/repositories/IRolRepository.java
Labels: bug, enhancement

#31 añadiendo 2 querys para la tabla appointment
  src/main/java/pe/edu/upc/taytagrupo5/controllers/AppointmentController.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/ListPatientsByDateDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/ListPatientsByStaffDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/repositories/IAppointmentRepository.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceimplements/AppointmentServiceImplement.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceinterfaces/IAppointmentService.java
Labels: enhancement

#32 Rama de emerzon
  src/main/java/pe/edu/upc/taytagrupo5/controllers/AppointmentController.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/AppointmentCountDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/AppointmentModeDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/repositories/IAppointmentRepository.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceimplements/AppointmentServiceImplement.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceinterfaces/IAppointmentService.java
  src/main/resources/application.properties
Labels: enhancement

#33 queries fixed
  src/main/java/pe/edu/upc/taytagrupo5/controllers/UserController.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/DateapointmentDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/dtos/QuantityUsersPerDatesDTO.java
  src/main/java/pe/edu/upc/taytagrupo5/repositories/IUserRepository.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceimplements/UserServiceImplement.java
  src/main/java/pe/edu/upc/taytagrupo5/serviceinterfaces/IUserService.java
Labels: bug

#34 cambios en appointment
  src/main/java/pe/edu/upc/taytagrupo5/dtos/AppointmentCountDTO.java
Labels: enhancement
